### ISSUE TITLE
1.0.4版本获取推文内容失败： Element "body > div > div > div.main-thread" not found

### ISSUE THREAD

**Issue by TheFairyTale** [Yamamoto-2/koishi-plugin-nitter-rss#5]
后台报错信息如下：
```

2024-03-02 13:51:29 [I] nitter-rss-apply 正在循环2024/3/2 13:51:29
2024-03-02 13:51:30 [W] app ctx.http.axios() is deprecated, use ctx.http() instead
2024-03-02 13:51:32 [S] nitter-rss-rss RSS解析成功: minatoaqua
2024-03-02 13:51:39 [E] nitter-rss-parseLinkInfo Error: Element "body > div > div > div.main-thread" not found.
                            at capturehtml (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\koishi-plugin-nitter-rss\lib\puppeteer.js:121:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async parseLinkInfo (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\koishi-plugin-nitter-rss\lib\parseLinkInfo.js:39:19)
                            at async sendMessages (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\koishi-plugin-nitter-rss\lib\index.js:137:36)
                            at async Timeout.interval [as _onTimeout] (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\koishi-plugin-nitter-rss\lib\index.js:171:9)
2024-03-02 13:51:39 [I] nitter-rss-apply 正在发送消息: http://nitter.esmailelbob.xyz/minatoaqua/status/1763803215672602853#m至r**:31*******
2024-03-02 13:51:39 [I] nitter-rss-apply 正在等待51秒
2024-03-02 13:52:30 [I] nitter-rss-apply 循环结束

```

此时可以在群内看到以下提示：
![image](https://github.com/Yamamoto-2/koishi-plugin-nitter-rss/assets/16740355/47b7cba7-fc2a-4c83-bfae-21a02168e407)

**Comment by TheFairyTale** [comment]
Koishi版本及系统信息：
System:
 - OS: Windows Server 2012 6.3.9600
 - CPU: (2) x64 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz

Binaries:
 - Node: 20.11.1
 - Yarn: 4.1.0

Koishi:
 - Core: 4.17.1
 - Console: 5.28.0

**Comment by Yamamoto-2** [comment]
nitter项目的所有镜像站都已经关闭了，因为推特的游客账号已经没法创建。你如果打算继续用这个项目的话，需要自己部署nitter实例，可以参考以下: 
https://github.com/zedeus/nitter
关于镜像站关闭的原因: 
https://github.com/zedeus/nitter/issues/1154

**Comment by TheFairyTale** [comment]
> nitter项目的所有镜像站都已经关闭了，因为推特的游客账号已经没法创建。你如果打算继续用这个项目的话，需要自己部署nitter实例，可以参考以下: https://github.com/zedeus/nitter 关于镜像站关闭的原因: [zedeus/nitter#1154](https://github.com/zedeus/nitter/issues/1154)

您好，我已经按照nitter 仓库中的指引部署了该程序。问一个题外话，您大致知道如何使用正常的twitter账号让nitter 运作吗，或者使用twitter 的api账号来使nitter 可以通过该账户获取基本推文。目前我配置任何一种twitter 的开发者账号的账户与密钥都不能让nitter正常查出推文

**Comment by TheFairyTale** [comment]
> nitter项目的所有镜像站都已经关闭了，因为推特的游客账号已经没法创建。你如果打算继续用这个项目的话，需要自己部署nitter实例，可以参考以下: https://github.com/zedeus/nitter 关于镜像站关闭的原因: [zedeus/nitter#1154](https://github.com/zedeus/nitter/issues/1154)

无论如何感谢您的这条回复，谢谢您！
